config/routes.rb
Rails.application.routes.draw do
  resources :ingredients
  resources :meal_types
  resources :locations
  resources :ratings
  resources :users do
    get :password_reset, on: :member
  end
  resources :menu_items
  resources :meals do
    resources :ratings
    get :user_rating, on: :member, controller: :ratings
  end
  resources :restaurants

  resource :session, only: [:new, :create, :destroy]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resource :update_jobs, only: [:new, :create]

  root "restaurants#index"

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/meal_types_controller.rb
class MealTypesController < ApplicationController
  before_action :set_meal_type, only: %i[ show edit update destroy ]

  # GET /meal_types or /meal_types.json
  def index
    @meal_types = MealType.all
  end

  # GET /meal_types/1 or /meal_types/1.json
  def show
  end

  # GET /meal_types/new
  def new
    @meal_type = MealType.new
  end

  # GET /meal_types/1/edit
  def edit
  end

  # POST /meal_types or /meal_types.json
  def create
    @meal_type = MealType.new(meal_type_params)

    respond_to do |format|
      if @meal_type.save
        format.html { redirect_to meal_type_url(@meal_type), notice: "Meal type was successfully created." }
        format.json { render :show, status: :created, location: @meal_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meal_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meal_types/1 or /meal_types/1.json
  def update
    respond_to do |format|
      if @meal_type.update(meal_type_params)
        format.html { redirect_to meal_type_url(@meal_type), notice: "Meal type was successfully updated." }
        format.json { render :show, status: :ok, location: @meal_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meal_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meal_types/1 or /meal_types/1.json
  def destroy
    @meal_type.destroy

    respond_to do |format|
      format.html { redirect_to meal_types_url, notice: "Meal type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meal_type
      @meal_type = MealType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meal_type_params
      params.require(:meal_type).permit(:name, :color, :price)
    end
end

app/helpers/meal_types_helper.rb
module MealTypesHelper
end

app/views/meal_types/_form.html.erb
<%= form_with(model: meal_type, class: "contents") do |form| %>
  <% if meal_type.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(meal_type.errors.count, "error") %> prohibited this meal_type from being saved:</h2>

      <ul>
        <% meal_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :color %>
    <%= form.text_field :color, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.text_field :price, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/meal_types/_meal_type.html.erb
<div id="<%= dom_id meal_type %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= meal_type.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Color:</strong>
    <%= meal_type.color %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Price:</strong>
    <%= meal_type.price %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this meal type", meal_type, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this meal type', edit_meal_type_path(meal_type), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/meal_types/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing meal type</h1>

  <%= render "form", meal_type: @meal_type %>

  <%= link_to "Show this meal type", @meal_type, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to meal types", meal_types_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/meal_types/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Meal types</h1>
    <%= link_to 'New meal type', new_meal_type_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="meal_types" class="min-w-full">
    <%= render @meal_types %>
  </div>
</div>

app/views/meal_types/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New meal type</h1>

  <%= render "form", meal_type: @meal_type %>

  <%= link_to 'Back to meal types', meal_types_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/meal_types/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @meal_type %>

    <%= link_to 'Edit this meal_type', edit_meal_type_path(@meal_type), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this meal_type', meal_type_path(@meal_type), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to meal_types', meal_types_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>