config/routes.rb
Rails.application.routes.draw do
  resources :ingredients
  resources :meal_types
  resources :locations
  resources :ratings
  resources :users do
    get :password_reset, on: :member
  end
  resources :menu_items
  resources :meals do
    resources :ratings
    get :user_rating, on: :member, controller: :ratings
  end
  resources :restaurants

  resource :session, only: [:new, :create, :destroy]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resource :update_jobs, only: [:new, :create]

  root "restaurants#index"

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :restaurant
  belongs_to :meal

  default_scope -> { includes :meal, :restaurant }
  scope :on_date, ->(date) {
    includes(meal: :meal_type)
      .where(menu_date: date)
  }
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  before_action :set_menu_item, only: %i[ show edit update destroy ]
  before_action :must_be_admin, except: [:index, :show]

  # GET /menu_items or /menu_items.json
  def index
    @menu_items = MenuItem.all
  end

  # GET /menu_items/1 or /menu_items/1.json
  def show
  end

  # GET /menu_items/new
  def new
    @menu_item = MenuItem.new
  end

  # GET /menu_items/1/edit
  def edit
  end

  # POST /menu_items or /menu_items.json
  def create
    @menu_item = MenuItem.new(menu_item_params)

    respond_to do |format|
      if @menu_item.save
        format.html { redirect_to menu_item_url(@menu_item), notice: "Menu item was successfully created." }
        format.json { render :show, status: :created, location: @menu_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menu_items/1 or /menu_items/1.json
  def update
    respond_to do |format|
      if @menu_item.update(menu_item_params)
        format.html { redirect_to menu_item_url(@menu_item), notice: "Menu item was successfully updated." }
        format.json { render :show, status: :ok, location: @menu_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_items/1 or /menu_items/1.json
  def destroy
    @menu_item.destroy

    respond_to do |format|
      format.html { redirect_to menu_items_url, notice: "Menu item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu_item
      @menu_item = MenuItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def menu_item_params
      params.require(:menu_item).permit(:restaurant_id, :meal_id, :menu_date)
    end
end

app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

app/views/menu_items/_form.html.erb
<%= form_with(model: menu_item) do |form| %>
  <% if menu_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(menu_item.errors.count, "error") %> prohibited this menu_item from being saved:</h2>

      <ul>
        <% menu_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :restaurant_id, style: "display: block" %>
    <%= form.number_field :restaurant_id %>
  </div>

  <div>
    <%= form.label :meal_id, style: "display: block" %>
    <%= form.number_field :meal_id %>
  </div>

  <div>
    <%= form.label :menu_date, style: "display: block" %>
    <%= form.datetime_field :menu_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/menu_items/_menu_item.html.erb
<section data-controller="modal" id="<%=dom_id(menu_item)%>">
  <button type=button
          data-action="click->modal#open"
          class="flex items-start gap-2 p-2 pl-4 w-full rounded-lg border-2 border-stone-700 hover:border-stone-600
          text-stone-300 hover:text-stone-100 transition-colors duration-100">
    <h4>
      <%= menu_item.meal.name %>
    </h4>
    <% unless menu_item.meal.meal_type.nil? %>
      <div class="flex gap-2 px-2 ml-auto rounded-lg bg-stone-700 border text-sm" style="border-color: <%= menu_item.meal.meal_type.color_style or "gray" %>">
        <span style="color: <%= menu_item.meal.meal_type.color_style or "gray" %>">
          <%= menu_item.meal.meal_type.name %>
        </span>
      </div>
      <%= render "partials/score_small", score: menu_item.meal.score %>
    <% end %>
  </button>

  <dialog data-modal-target="modal"
          data-action="click->modal#close"
          class="fixed top-0 w-[100vw] h-[100vh] bg-transparent backdrop-brightness-50 backdrop-blur-md transition-opacity duration-200 z-10 opacity-0">
    <div class="container mx-auto m-4 rounded-lg bg-stone-900/60 transition-transform duration-200 -translate-y-full"
         data-modal-target="modalContainer"
         data-controller="clickCapture"
         data-action="click->clickCapture#stopPropagation"
    >
      <header class="flex gap-4 mb-4 items-end border-b-2 border-stone-700 py-2 px-4">
        <p class="text-stone-400"><%= menu_item.meal.name %> in <%= menu_item.restaurant.name %> on <%= menu_item.menu_date %></p>
        <button type="button" class="hidden md:block ml-auto text-stone-200" data-action="click->modal#close">Close</button>
      </header>
      <article>
        <%= turbo_frame_tag "meal_details", src: menu_item.meal, loading: "lazy" do %>
          <p class="text-stone-400 text-sm py-6 animate-bounce">Loading details...</p>
        <% end %>
        <%= turbo_frame_tag "user_rating", src: user_rating_meal_path(menu_item.meal), loading: "lazy" do %>
          <p class="text-stone-400 text-sm py-6 animate-bounce">Loading rating...</p>
        <% end %>
      </article>
      <button type="button" class="md:hidden mt-auto w-full py-2 border-t-2 border-teal-700 text-teal-600" data-action="click->modal#close">Close</button>
    </div>
  </dialog>
</section>

app/views/menu_items/edit.html.erb
<h1>Editing menu item</h1>

<%= render "form", menu_item: @menu_item %>

<br>

<div>
  <%= link_to "Show this menu item", @menu_item %> |
  <%= link_to "Back to menu items", menu_items_path %>
</div>

app/views/menu_items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Menu items</h1>

<div id="menu_items">
  <% @menu_items.each do |menu_item| %>
    <%= render menu_item %>
    <p>
      <%= link_to "Show this menu item", menu_item %>
    </p>
  <% end %>
</div>

<%= link_to "New menu item", new_menu_item_path %>

app/views/menu_items/new.html.erb
<h1>New menu item</h1>

<%= render "form", menu_item: @menu_item %>

<br>

<div>
  <%= link_to "Back to menu items", menu_items_path %>
</div>

app/views/menu_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @menu_item %>

<div>
  <%= link_to "Edit this menu item", edit_menu_item_path(@menu_item) %> |
  <%= link_to "Back to menu items", menu_items_path %>

  <%= button_to "Destroy this menu item", @menu_item, method: :delete %>
</div>