config/routes.rb
Rails.application.routes.draw do
  resources :ingredients
  resources :meal_types
  resources :locations
  resources :ratings
  resources :users do
    get :password_reset, on: :member
  end
  resources :menu_items
  resources :meals do
    resources :ratings
    get :user_rating, on: :member, controller: :ratings
  end
  resources :restaurants

  resource :session, only: [:new, :create, :destroy]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resource :update_jobs, only: [:new, :create]

  root "restaurants#index"

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :meal

  validates :score, numericality: { minimum: 1, maximum: 5 }
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: %i[ show edit update destroy ]
  before_action :must_sign_in, except: [:index, :user_rating]

  # GET /ratings or /ratings.json
  def index
    @ratings = Rating.all
  end

  def user_rating
    @all_ratings = Rating.all.includes(:user).where(meal_id: params[:id])
    @average_score = @all_ratings.sum(&:score) / @all_ratings.count.to_f if @all_ratings.count > 0
    @rating = Rating.where(user_id: current_user&.id, meal_id: params[:id]).first_or_initialize
    render partial: "ratings/user_rating", layout: false
  end

  # GET /ratings/1 or /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end

  # POST /ratings or /ratings.json
  def create
    @rating = Rating.new(rating_params)

    if @rating.save
      @all_ratings = Rating.all.includes(:user).where(meal_id: @rating.meal_id).to_a.push(@rating).uniq(&:id).sort_by(&:updated_at)
      @average_score = @all_ratings.sum(&:score) / @all_ratings.count.to_f
      render partial: "ratings/user_rating", layout: false
    end
  end

  # PATCH/PUT /ratings/1 or /ratings/1.json
  def update
    can_edit

    if @rating.update(rating_params)
      @all_ratings = Rating.all.includes(:user).where(meal_id: @rating.meal_id).to_a.push(@rating).uniq(&:id).sort_by(&:updated_at)
      @average_score = @all_ratings.sum(&:score) / @all_ratings.count.to_f
      render partial: "ratings/user_rating", layout: false
    end
  end

  # DELETE /ratings/1 or /ratings/1.json
  def destroy
    can_edit

    @rating.destroy
    @rating = Rating.new(meal_id: @rating.meal_id, user_id: current_user&.id)
    @all_ratings = Rating.includes(:user).where(meal_id: @rating.meal_id).to_a.uniq(&:id).sort_by(&:updated_at)
    @average_score = @all_ratings.sum(&:score) / @all_ratings.count.to_f if @all_ratings.count > 0
    render partial: "ratings/user_rating", layout: false
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rating_params
      params.require(:rating).permit(:meal_id, :score).merge(user_id: current_user&.id)
    end

    def can_edit
      unless @rating.user == current_user
        redirect_to root_path, notice: "You can only edit your own ratings."
      end
    end

    def set_average_score
      @average_score = Rating.where(meal_id: @rating.meal_id).average(:score)
    end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= form_with(model: rating, class: "contents", data: { "controller" => "ratingForm" }) do |form| %>
  <%= form.hidden_field :meal_id %>
  <%= form.hidden_field :user_id %>
  <%= form.hidden_field :score, data: { "ratingForm-target": "scoreField", } %>

  <div class="flex gap-2 mx-2 mb-2">
    <% (1..5).each do |score| %>
      <%= form.submit score,
                      class: "rounded-lg py-3 px-5 #{(rating.score and score <= rating.score) ? "bg-blue-600" : ""} hover:bg-blue-600/50 border border-blue-600 text-white font-medium cursor-pointer",
                      data: { action: "ratingForm#setScore", "score": score } %>
    <% end %>
  </div>

<% end %>

app/views/ratings/_rating.html.erb
<div id="<%= dom_id rating %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Meal:</strong>
    <%= rating.meal_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= rating.user_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Rating:</strong>
    <%= rating.rating %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this rating", rating, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this rating', edit_rating_path(rating), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/ratings/_user_rating.html.erb
<%= turbo_frame_tag "user_rating" do %>
  <section>
    <div class="flex flex-col items-center w-full">
      <h2 class="text-stone-300 mb-2">Rate this meal</h2>
      <% if current_user %>
        <%= render partial: "ratings/form", locals: { rating: @rating }%>
        <% unless @rating.new_record? %>
          <%= button_to "Reset", rating_path(@rating), method: :delete, class: "text-stone-500 text-sm hover:text-red-600" %>
        <% end %>
      <% else %>
        <%= link_to "Log in to rate this meal", login_path, class: "text-teal-500 p-1 rounded-lg border-2 border-teal-600" %>
      <% end %>
    </div>
    <div class="border-stone-700 border-t-2 mt-8 w-full" ></div>
    <% if @average_score %>
      <div class="flex flex-col gap-y-4 md:flex-row items-stretch w-full">
        <p class="text-stone-300 text-lg mb-4 py-4 px-8">Average rating is <%= render "partials/score", score: @average_score %></p>
        <div class="border-stone-700 border-l-2 w-[1rem]" ></div>
        <div class="py-4 px-8 flex-grow">
          <h3 class="text-stone-300 mb-4 text-lg">All ratings</h3>
          <ul>
            <% @all_ratings.each do |rating| %>
              <li class="mb-2">
                <p class="text-stone-400 text-xs"><%= rating.updated_at.strftime("%a, %b %d") %></p>
                <p class="text-stone-300"><%= render "partials/score", score: rating.score %> - <%= rating.user.username %></p>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    <% else %>
      <p class="text-stone-400 py-4 px-8 ">No ratings yet</p>
    <% end %>


  </section>
<% end %>

app/views/ratings/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing rating</h1>

  <%= render "form", rating: @rating %>

  <%= link_to "Show this rating", @rating, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to ratings", ratings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/ratings/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Ratings</h1>
    <%= link_to 'New rating', new_rating_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="ratings" class="min-w-full">
    <%= render @ratings %>
  </div>
</div>

app/views/ratings/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New rating</h1>

  <%= render "form", rating: @rating %>

  <%= link_to 'Back to ratings', ratings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/ratings/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @rating %>

    <%= link_to 'Edit this rating', edit_rating_path(@rating), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this rating', rating_path(@rating), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to ratings', ratings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>